#!/usr/bin/env python3
"""Produce raw-canonical and normalized structural diffs for OVAL XML round trips."""
from __future__ import annotations
import argparse, difflib, re
from pathlib import Path
from lxml import etree as E

OD="http://oval.mitre.org/XMLSchema/oval-definitions-5"
OC="http://oval.mitre.org/XMLSchema/oval-common-5"

REF_ATTRS={"test_ref","object_ref","state_ref","var_ref","definition_ref"}
ID_ATTR="id"

def parse(path:Path):
    parser=E.XMLParser(remove_blank_text=True,remove_comments=False)
    return E.parse(str(path),parser)

def canonical_lines(tree):
    data=E.tostring(tree,method="c14n",with_comments=True)
    return data.decode("utf-8").splitlines()

def strip_noise(tree):
    root=tree.getroot()

    # Remove comments and generator metadata: provenance/serialization noise only.
    for c in root.xpath("//comment()"):
        c.getparent().remove(c)
    for g in root.xpath("//*[local-name()='generator' and namespace-uri()=$ns]",ns=OD):
        g.getparent().remove(g)

    # Remove metadata text that is intentionally regenerated by this harness.
    for md in root.xpath("//*[local-name()='metadata' and namespace-uri()=$ns]",ns=OD):
        parent=md.getparent()
        if parent is not None:
            parent.remove(md)

    # Canonicalize all OVAL IDs and references by semantic type and encounter order.
    maps={"def":{},"tst":{},"obj":{},"ste":{},"var":{}}
    counters={k:1 for k in maps}

    def kind(v):
        for k,token in [("def",":def:"),("tst",":tst:"),("obj",":obj:"),("ste",":ste:"),("var",":var:")]:
            if token in v:
                return k
        return None

    def canon(v):
        k=kind(v)
        if not k:
            return v
        if v not in maps[k]:
            maps[k][v]=f"{k}:{counters[k]}"
            counters[k]+=1
        return maps[k][v]

    # First assign declarations in document order, then rewrite refs.
    for el in root.iter():
        if ID_ATTR in el.attrib:
            el.attrib[ID_ATTR]=canon(el.attrib[ID_ATTR])
    for el in root.iter():
        for a in REF_ATTRS:
            if a in el.attrib:
                el.attrib[a]=canon(el.attrib[a])
        # object_reference/filter store refs as text.
        lname=E.QName(el).localname if isinstance(el.tag,str) else ""
        if lname in {"object_reference","filter"} and el.text and el.text.strip():
            el.text=canon(el.text.strip())

    # Normalize version/comment/deprecated attributes that don't alter the exercised
    # behavior being compared by this harness.
    for el in root.iter():
        for a in ("version","comment"):
            el.attrib.pop(a,None)
        if el.attrib.get("deprecated")=="false":
            el.attrib.pop("deprecated",None)

    return tree

def pretty_lines(tree):
    return E.tostring(tree,pretty_print=True,encoding="unicode").splitlines()

def write_diff(a,b,label_a,label_b,out):
    text="\n".join(difflib.unified_diff(a,b,fromfile=label_a,tofile=label_b,lineterm=""))+"\n"
    out.write_text(text,encoding="utf-8")
    return text

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("source",type=Path)
    ap.add_argument("regenerated",type=Path)
    ap.add_argument("--out-dir",type=Path,required=True)
    args=ap.parse_args()
    args.out_dir.mkdir(parents=True,exist_ok=True)

    a=parse(args.source); b=parse(args.regenerated)
    raw=write_diff(canonical_lines(a),canonical_lines(b),
                   str(args.source),str(args.regenerated),
                   args.out_dir/"raw-c14n.diff")

    an=strip_noise(parse(args.source)); bn=strip_noise(parse(args.regenerated))
    normalized=write_diff(pretty_lines(an),pretty_lines(bn),
                          "source-normalized.xml","regenerated-normalized.xml",
                          args.out_dir/"normalized-structural.diff")
    (args.out_dir/"source-normalized.xml").write_text(
        E.tostring(an,pretty_print=True,encoding="unicode"),encoding="utf-8")
    (args.out_dir/"regenerated-normalized.xml").write_text(
        E.tostring(bn,pretty_print=True,encoding="unicode"),encoding="utf-8")

    print(f"raw_diff_lines={len(raw.splitlines())}")
    print(f"normalized_diff_lines={len(normalized.splitlines())}")
    # Structural differences are diagnostic, not automatically failures: some
    # source decomposition may intentionally normalize while preserving semantics.

if __name__=="__main__":
    main()
